name: Run Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Allure
      run: |
        npm install -g allure-commandline --save-dev

    - name: Run Tests
      run: |
        pytest --alluredir=allure-results

    - name: Generate Allure Report
      run: |
        allure generate allure-results -o allure-report --clean

    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
